
query groupsForIndex {
    annonces {
        name
        _id
        creator {
            username
        }
        sport {
            name
        }
        annonces {
            _id
        }
    }
}

query annonceForIndex {
    annonces {
        date
        _id
        name
        creator {
            username
        }
        sport { 
            name
        }
        group {
            name
        }
    }
}

query groupDetail ($id: String) {
     annonceById (id: $id) {
         name
         sport {
             name
         }
        creator {
            username
        }
         annonces {
             date
             places
             subscribers {
                 username
             }
         }
     }
}

query groups ($id: String) {
     annonces (annonce: $id) {
        date
        places
        subscribers {
            username
        }
        annonce {
            sport {
                name
            }
        }
     }
}

mutation subscribe($userId: String, $annonceId: String) {
    subscribe(subscribe: { annonceId: $annonceId, userId: $userId }) {
        _id
        subscribers {
            username
        }
    }
}

query annonceById ($id: String) {
     annonce (id: $id) {
         _id
        date
        places
        name
        subscribers {
            username
        }
        sport {
            name
        }
        address {
            latitude
            longitude
            streetNumber
            route
            locality
            postalCode
        }
     }
}

mutation createAnnonce(
    $name: String,
    $creator: String,
    $sport: String,
    $date: Date,
    $streetNumber: String,
    $route: String,
    $locality: String,
    $country: String,
    $postalCode: String,
    $latitude: Float,
    $longitude: Float,
    $addressName: String,
    $placeId: String,
    $places: Int
) {
    addAnnonce(
        annonce: { name: $name, creator: $creator, sport: $sport, date: $date, places: $places }
        address: {
            streetNumber: $streetNumber,
            route: $route,
            locality: $locality,
            country: $country,
            postalCode: $postalCode,
            latitude: $latitude,
            longitude: $longitude,
            addressName: $addressName,
            placeId: $placeId
        }
    ) {
        _id
    }
}

query userAutoComplete ($userContain: String) {
    searchUser(userContain: $userContain) {
        _id
        lastName
        firstName
        username
    }
}