
query groupsForIndex {
    annonces {
        name
        _id
        creator {
            username
        }
        sport {
            name
        }
        annonces {
            _id
        }
    }
}

query annonceForIndex {
    annonces {
        date
        _id
        name
        creator {
            username
        }
        sport { 
            name
        }
        group {
            name
        }
    }
}

query groupDetail ($id: String) {
     annonceById (id: $id) {
         name
         sport {
             name
         }
        creator {
            username
        }
         annonces {
             date
             places
             subscribers {
                 username
             }
         }
     }
}

query groups ($id: String) {
     annonces (annonce: $id) {
        date
        places
        subscribers {
            username
        }
        annonce {
            sport {
                name
            }
        }
     }
}

query annonceById ($id: String) {
     annonce (id: $id) {
        date
        places
        subscribers {
            username
        }
        sport {
            name
        }
     }
}

mutation createAnnonce( $name: String, $creator: String, $sport: String, $date: Date) {
    addAnnonce(annonce: { name: $name, creator: $creator, sport: $sport, date: $date }) {
        name
        _id
        sport { name }
    }
}

query userAutoComplete ($userContain: String) {
    searchUser(userContain: $userContain) {
        _id
        lastName
        firstName
        username
    }
}